name: Build and Attest Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the Docker image (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build-and-attest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/dpembo/backuphub/hub:latest
            ghcr.io/dpembo/backuphub/hub:${{ inputs.version }}
          labels: |
            org.opencontainers.image.title=dpembo/backuphub/hub
            org.opencontainers.image.version=${{ inputs.version }}

      - name: Attest build provenance
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/dpembo/backuphub/hub
          subject-digest: ${{ steps.build-and-push.outputs.digest }}
          push-to-registry: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
