# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      verno:
        description: 'Release Verson'
        required: true

permissions:
  id-token: write
  contents: read
  attestations: write
  packages: write

jobs:
  build-and-attest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/dpembo/backuphub
          tags: |
            type=raw,value=hub,enable=${{ !cancelled() }}

      - name: Build and push Docker image to GHCR
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=backuphub,annotation-index.org.opencontainers.image.description=BackupHub is a lightweight yet powerful solution for managing and scheduling shell-based executions across a local area network

      - name: Attest build provenance
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/dpembo/backuphub
          subject-digest: ${{ steps.build-and-push.outputs.digest }} # Use the digest from the build step
          push-to-registry: true
          show-summary: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          DOCKER_METADATA_OUTPUT_VERSION: main
          DOCKER_METADATA_OUTPUT_TAGS: hub:main
          DOCKER_METADATA_OUTPUT_LABELS: |
            org.opencontainers.image.title=BackupHub
            org.opencontainers.image.description=BackupHub is a lightweight yet powerful solution for managing and scheduling shell-based executions across a local area network
            org.opencontainers.image.url=https://github.com/dpembo/BackupHub
            org.opencontainers.image.source=https://github.com/dpembo/BackupHub
            org.opencontainers.image.version=main
            org.opencontainers.image.created=2025-04-08T20:14:49.192Z
            org.opencontainers.image.revision=0ff1e5afe0e79a246cf8bfce787926bf420ca9a7
            org.opencontainers.image.licenses=Apache-2.0

      - name: Print attestation summary (optional)
        run: echo "Provenance attestation completed for ${{ steps.build-and-push.outputs.digest }}"

        
