name: Build and Attest Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the Docker image (e.g., v1.0.0)'
        required: true
        type: string

# Add this permissions block
permissions:
  id-token: write
  contents: read
  attestations: write
  packages: write
  
jobs:
  build-and-attest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version and create agent tar
        run: |
          replace_text() {
              local search_text="$1"
              local replacement_text="$2"
              local file_path="$3"

              # Check if the file exists
              if [ ! -f "$file_path" ]; then
                  echo "File $file_path does not exist."
                  exit 1
              fi

              # Perform the replacement
              sed -i "s/$search_text/$replacement_text/g" "$file_path"
          }

          # Set version from workflow input
          version="${{ inputs.version }}"
          if [ -z "$version" ]; then
              echo "Version is not provided."
              exit 1
          fi

          findText="var version=\"%%UNDEFINED%%\";"
          replText="var version=\"${version}\";"

          echo "Setting version number in hub and agent build"
          replace_text "$findText" "$replText" version.js
          replace_text "$findText" "$replText" ./agent/version.js

          echo "Create the agent tar for install from the web ux"
          tar -cvf ./public/agent/agent.tar -C ./agent .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push BackupHub/hub image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/dpembo/backuphub/hub:latest
            ghcr.io/dpembo/backuphub/hub:${{ inputs.version }}
          labels: |
            org.opencontainers.image.title=dpembo/backuphub/hub
            org.opencontainers.image.version=${{ inputs.version }}

      - name: Attest build provenance for BackupHub/hub
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/dpembo/backuphub/hub
          subject-digest: ${{ steps.build-and-push.outputs.digest }}
          push-to-registry: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backuphub/agent image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./agent/Dockerfile
          push: true
          tags: |
            ghcr.io/dpembo/backuphub/agent:latest
            ghcr.io/dpembo/backuphub/agent:${{ inputs.version }}
          labels: |
            org.opencontainers.image.title=dpembo/backuphub/agent
            org.opencontainers.image.version=${{ inputs.version }}

      - name: Attest build provenance for backuphub/agent
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/dpembo/backuphub/agent
          subject-digest: ${{ steps.build-and-push.outputs.digest }}
          push-to-registry: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

